### ISSUE TITLE
Not able to see old legacy content

### ISSUE THREAD

**Issue by DarkBuccaneer** [Polkadoty/armada-list-builder#68]
Me and my friend recently found this website, and are both thrilled to use it, except I can’t use my features other than the new legacy content. Whenever I flip the switch that is supposed to give  me the old content nothing happened. I also restart the page and flush the thingy below the settings. It’s also worth noting that if I ever turn off the tournament mode, and then either enter a faction menu or reload the page, the tournament mode is back on. I would love some help, and would like to say that I love your website and the work you are doing. Thanks!!

**Comment by Polkadoty** [comment]
This bug just showed up today. I'm working on fixing it later today and I'll let you know when it's fixed :)

**Comment by DarkBuccaneer** [comment]
Thank you so much, really appreciate it

**Comment by DarkBuccaneer** [comment]
Totally fixed
